### ISSUE TITLE
Backtrace loop on new SDK 3.X esp8266

### ISSUE THREAD

**Issue by vslinuxdotnet** [DonKracho/Arduino--GT-WT-02-Decoder#7]
Hello,
 I get a backtrace because the interrupt ISR  function is not in IRAM

You need to change from 
`void receiveWTsignal()`
to
`void ICACHE_RAM_ATTR receiveWTsignal()`

That's all for now.

VS

**Comment by DonKracho** [comment]
Hi vslinuxdotnet,

you are right, I fixed it. THX
